# Generated by Django 4.0.4 on 2022-11-17 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='createdDate',
        ),
    ]
