# Generated by Django 4.0.4 on 2022-10-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='BloodPressure',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Pulse',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='Respiration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
