# Generated by Django 4.0.4 on 2022-10-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_report_bloodpressure_alter_report_pulse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='user_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
