# Generated by Django 4.0.4 on 2022-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_report_createddate_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(null=True),
        ),
    ]
