# Generated by Django 4.0.4 on 2022-10-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentDate',
            new_name='appointment',
        ),
    ]
